### ISSUE TITLE
Entrega Trabajo Práctico N°2

### ISSUE THREAD

**Issue by LeoSabaLagos** [alesiosaba/2020_K2001_Grupo_10#2]
Solicito corrección del trabajo práctico: @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Estimados,

@LeoSabaLagos @marciondg @alesiosaba @francisco-franchi 

El trabajo está IMPECABLE. Muy muy bueno.
El código está muy prolijo además de que cumple con todas las funcionalidades y la interfaz es muy clara.

FELICITACIONES !

Nota: 10

=)
