### ISSUE TITLE
Entrega Trabajo Práctico N°4

### ISSUE THREAD

**Issue by marciondg** [alesiosaba/2020_K2001_Grupo_10#4]
Solicitamos corrección del trabajo práctico: @santiagoferreiros 

Nos quedamos con varias dudas que esperamos canalizarlas en nuestro próximo encuentro por meet.
Saludos
_Grupo 10_

**Comment by santiagoferreiros** [comment]
Marcio,
Lo canalizamos en nuestro próximo encuentro.
Me estaré poniendo en contacto con cada grupo.
Saludos,
Santiago
